quadrantChart
    title Financial Foundation
    x-axis Net Worth --> Income
    y-axis Living Below Your Means --> Living Above Your Means
    quadrant-1 Debt, Struggle
    quadrant-2 Debt, Worry
    quadrant-3 Generational Wealth
    quadrant-4 Surplus, Comfort, Peace of Mind
    Campaign A: [0.3, 0.6]
    Campaign B: [0.45, 0.23]
    Campaign C: [0.57, 0.69]
    Campaign D: [0.78, 0.34]
    Campaign E: [0.40, 0.34]
    Campaign F: [0.35, 0.78]
