%%{init: {'theme':'forest'}}%%
mindmap
  root)Financial Literacy(
    {{Lifestyles}}
      Live above your means
      Live at your means
      Live below your means
    {{Risks}}
      Inflation
      Market Risk | Volatility
      Tax
      Health
    {{Income Types}}
      Active
      Passive
      Single Stream
      Multi Stream
    {{Guiding Principles}}
      Net Worth
        Assets
        Liabilities
      Income
        Revenue
        Expenses
    {{Dimensions}}
      People
      Time
      Energy
      Knowledge
      Material
